import {asCircle,asLinePair,bumpIdSeqFrom,deleteWithDependents,existingPointNames,getPoint,newId,pickOrCreatePoint,recompute} from "./engine"; import {nextPointName} from "./format"; import {dist} from "./math"; import type {Constraint,GeoObject,PendingAction,PointObj,Tool} from "./types";
export const emptyPending=(tool:Tool):PendingAction=>({tool,ids:[]}); export interface ClickResult{objects:GeoObject[];pending:PendingAction|null;selected:string[];status:string}
function namedPoint(objects:GeoObject[],extra:Partial<PointObj>&{constraint:PointObj["constraint"]}):PointObj{return{kind:"point",id:newId("p"),name:extra.hidden?"":nextPointName(existingPointNames(objects)),x:0,y:0,...extra}}
function vertsOf(t:GeoObject){if(t.kind==="point")return[t.id];if(t.kind==="segment"||t.kind==="line"||t.kind==="ray")return[t.a,t.b];if(t.kind==="circle")return[t.center,t.through];if(t.kind==="polygon")return t.verts;if(t.kind==="angle")return[t.a,t.v,t.b];return[]}
function mapShape(objects:GeoObject[],targetId:string,make:(srcId:string)=>Constraint){const t=objects.find(o=>o.id===targetId);if(!t)return objects;const ids=vertsOf(t);if(!ids.length)return objects;let next=objects,images:string[]=[];for(const id of ids){const p=namedPoint(next,{constraint:make(id)});next=[...next,p];images.push(p.id)}if((t.kind==="segment"||t.kind==="line"||t.kind==="ray")&&images[0]&&images[1])next=[...next,{kind:t.kind,id:newId(t.kind==="segment"?"s":t.kind==="ray"?"r":"l"),a:images[0],b:images[1]}];if(t.kind==="circle"&&images[0]&&images[1])next=[...next,{kind:"circle",id:newId("c"),center:images[0],through:images[1]}];if(t.kind==="polygon"&&images.length>=3)next=[...next,{kind:"polygon",id:newId("g"),verts:images,fill:"rgba(33,86,76,.12)"}];return recompute(next)}
export function constructMidpoint(o:GeoObject[],a:string,b:string){return recompute([...o,namedPoint(o,{constraint:{type:"midpoint",a,b}})])}
export function constructPerpendicular(o:GeoObject[],lineId:string,pointId:string){const pair=asLinePair(o,lineId),p=getPoint(o,pointId);if(!pair||!p)return o;const foot=namedPoint(o,{constraint:{type:"foot",p:pointId,a:pair.a,b:pair.b}}),far=namedPoint([...o,foot],{hidden:true,constraint:{type:"offset-perp",origin:pointId,from:pair.a,to:pair.b}});return recompute([...o,foot,far,{kind:"line",id:newId("l"),a:pointId,b:far.id},{kind:"segment",id:newId("s"),a:pointId,b:foot.id,dashed:true}])}
export function constructParallel(o:GeoObject[],lineId:string,pointId:string){const pair=asLinePair(o,lineId);if(!pair)return o;const far=namedPoint(o,{hidden:true,constraint:{type:"offset",origin:pointId,from:pair.a,to:pair.b}});return recompute([...o,far,{kind:"line",id:newId("l"),a:pointId,b:far.id}])}
export function constructPerpBisector(o:GeoObject[],a:string,b:string){const m=namedPoint(o,{constraint:{type:"midpoint",a,b}}),far=namedPoint([...o,m],{hidden:true,constraint:{type:"offset-perp",origin:m.id,from:a,to:b}});return recompute([...o,m,far,{kind:"line",id:newId("l"),a:m.id,b:far.id}])}
export function constructAngleBisector(o:GeoObject[],a:string,v:string,b:string){const p=namedPoint(o,{constraint:{type:"on-bisector",a,v,b,dist:2.5}});return recompute([...o,p,{kind:"ray",id:newId("r"),a:v,b:p.id}])}
export function constructIntersect(o:GeoObject[],id1:string,id2:string){const l1=asLinePair(o,id1),l2=asLinePair(o,id2),c1=asCircle(o,id1),c2=asCircle(o,id2);if(l1&&l2)return recompute([...o,namedPoint(o,{constraint:{type:"intersection-ll",a1:l1.a,b1:l1.b,a2:l2.a,b2:l2.b}})]);const line=l1??l2,circle=c1??c2;if(line&&circle){const p0=namedPoint(o,{constraint:{type:"intersection-lc",a:line.a,b:line.b,center:circle.center,through:circle.through,which:0}}),p1=namedPoint([...o,p0],{constraint:{type:"intersection-lc",a:line.a,b:line.b,center:circle.center,through:circle.through,which:1}});return recompute([...o,p0,p1])}if(c1&&c2){const p0=namedPoint(o,{constraint:{type:"intersection-cc",c1:c1.center,t1:c1.through,c2:c2.center,t2:c2.through,which:0}}),p1=namedPoint([...o,p0],{constraint:{type:"intersection-cc",c1:c1.center,t1:c1.through,c2:c2.center,t2:c2.through,which:1}});return recompute([...o,p0,p1])}return o}
export const constructReflect=(o:GeoObject[],t:string,m:string)=>{const p=asLinePair(o,m);return p?mapShape(o,t,src=>({type:"reflect",src,a:p.a,b:p.b})):o}; export const constructRotate90=(o:GeoObject[],s:string,c:string)=>o.find(x=>x.id===s)?mapShape(o,s,id=>({type:"rotate",src:id,center:c,angle:Math.PI/2})):o; export const constructTranslate=(o:GeoObject[],t:string,f:string,to:string)=>mapShape(o,t,src=>({type:"translate",src,from:f,to}));
export function constructCompass(o:GeoObject[],f:string,t:string,c:string){const through=namedPoint(o,{hidden:true,constraint:{type:"offset",origin:c,from:f,to:t}});return recompute([...o,through,{kind:"circle" as const,id:newId("c"),center:c,through:through.id}])}
function twoPointShape(o:GeoObject[],a:string,b:string,kind:"segment"|"line"|"ray"|"circle"){if(a===b)return o;if(kind==="circle")return[...o,{kind:"circle",id:newId("c"),center:a,through:b}];return[...o,{kind,id:newId(kind==="segment"?"s":kind==="ray"?"r":"l"),a,b}]}
export function handleCanvasClick(objects:GeoObject[],tool:Tool,pending:PendingAction|null,world:{x:number;y:number},scale:number,snap:boolean,hitId:string|null,hitKind:string|null):ClickResult{bumpIdSeqFrom(objects);if(tool==="delete")return hitId?{objects:deleteWithDependents(objects,[hitId]),pending:null,selected:[],status:"حذف شد"}:{objects,pending:null,selected:[],status:"شیئی را برای حذف انتخاب کنید"};if(tool==="select")return{objects,pending:null,selected:hitId?[hitId]:[],status:hitId?"انتخاب شد":""};if(tool==="point"){const r=pickOrCreatePoint(objects,world,scale,snap,true);return{objects:r.objects,pending:null,selected:[r.id],status:"نقطه گذاشته شد"}}const need:Partial<Record<Tool,number>>={segment:2,line:2,ray:2,circle:2,midpoint:2,angle:3,"angle-bisector":3,"perp-bisector":2,compass:3};
if(tool==="polygon"){const ids=pending?.tool==="polygon"?[...pending.ids]:[];if(ids.length>=3){const first=getPoint(objects,ids[0]!);if(first&&dist(first,world)<16/scale){const poly={kind:"polygon" as const,id:newId("g"),verts:ids,fill:"rgba(33,86,76,.12)"};return{objects:[...objects,poly],pending:null,selected:[poly.id],status:"چندضلعی بسته شد"}}}const r=pickOrCreatePoint(objects,world,scale,snap,true);if(!ids.includes(r.id))ids.push(r.id);return{objects:r.objects,pending:{tool,ids},selected:ids,status:"رأس بعدی؛ برای بستن روی نقطهٔ اول بزنید"}}
if(tool==="perpendicular"||tool==="parallel"){const ids=pending?.tool===tool?[...pending.ids]:[];if(!ids.length){if(hitId&&(hitKind==="segment"||hitKind==="line"||hitKind==="ray"))return{objects,pending:{tool,ids:[hitId]},selected:[hitId],status:"حالا یک نقطه انتخاب کنید"};return{objects,pending,selected:[],status:"ابتدا یک خط یا پاره‌خط را انتخاب کنید"}}const r=pickOrCreatePoint(objects,world,scale,snap,true),next=tool==="perpendicular"?constructPerpendicular(r.objects,ids[0]!,r.id):constructParallel(r.objects,ids[0]!,r.id);return{objects:next,pending:null,selected:[],status:tool==="perpendicular"?"عمود رسم شد":"موازی رسم شد"}}
if(tool==="intersect"){const ids=pending?.tool==="intersect"?[...pending.ids]:[];if(!hitId||!["segment","line","ray","circle"].includes(hitKind??""))return{objects,pending,selected:ids,status:"دو خط، خط و دایره، یا دو دایره را انتخاب کنید"};ids.push(hitId);if(ids.length<2)return{objects,pending:{tool,ids},selected:ids,status:"شیء دوم را انتخاب کنید"};return{objects:constructIntersect(objects,ids[0]!,ids[1]!),pending:null,selected:[],status:"نقطهٔ برخورد ساخته شد"}}
if(tool==="reflect"){const ids=pending?.tool==="reflect"?[...pending.ids]:[];if(!ids.length){if(!hitId)return{objects,pending,selected:[],status:"نقطه یا شکل را انتخاب کنید"};return{objects,pending:{tool,ids:[hitId]},selected:[hitId],status:"خط آینه را انتخاب کنید"}}if(!["segment","line","ray"].includes(hitKind??""))return{objects,pending,selected:ids,status:"خط تقارن را انتخاب کنید"};return{objects:constructReflect(objects,ids[0]!,hitId!),pending:null,selected:[],status:"تصویر ساخته شد"}}
if(tool==="rotate90"){const ids=pending?.tool==="rotate90"?[...pending.ids]:[];if(!ids.length){if(!hitId)return{objects,pending,selected:[],status:"نقطه یا شکل را انتخاب کنید"};return{objects,pending:{tool,ids:[hitId]},selected:[hitId],status:"مرکز دوران را انتخاب کنید"}}const r=pickOrCreatePoint(objects,world,scale,snap,true);return{objects:constructRotate90(r.objects,ids[0]!,r.id),pending:null,selected:[],status:"دوران ۹۰ درجه انجام شد"}}
if(tool==="translate"){const ids=pending?.tool==="translate"?[...pending.ids]:[];if(!ids.length){if(!hitId)return{objects,pending,selected:[],status:"شکل را انتخاب کنید"};return{objects,pending:{tool,ids:[hitId]},selected:[hitId],status:"ابتدای بردار انتقال را بزنید"}}const r=pickOrCreatePoint(objects,world,scale,snap,true);ids.push(r.id);if(ids.length<3)return{objects:r.objects,pending:{tool,ids},selected:ids,status:ids.length===2?"انتهای بردار را بزنید":"ابتدای بردار را بزنید"};return{objects:constructTranslate(r.objects,ids[0]!,ids[1]!,ids[2]!),pending:null,selected:[],status:"انتقال انجام شد"}}
if(tool==="compass"&&(!pending||pending.tool!==tool||!pending.ids.length)&&hitKind==="segment"&&hitId){const p=asLinePair(objects,hitId);if(p)return{objects,pending:{tool,ids:[p.a,p.b]},selected:[hitId],status:"مرکز دایره را انتخاب کنید"}}if(tool==="midpoint"&&(hitKind==="segment"||hitKind==="line"||hitKind==="ray")&&hitId){const p=asLinePair(objects,hitId);if(p)return{objects:constructMidpoint(objects,p.a,p.b),pending:null,selected:[],status:"نقطهٔ وسط ساخته شد"}}if(tool==="perp-bisector"&&hitKind==="segment"&&hitId){const p=asLinePair(objects,hitId);if(p)return{objects:constructPerpBisector(objects,p.a,p.b),pending:null,selected:[],status:"عمودمنصف رسم شد"}}
const count=need[tool];if(count){const ids=pending?.tool===tool?[...pending.ids]:[],r=pickOrCreatePoint(objects,world,scale,snap,true);if(!ids.includes(r.id))ids.push(r.id);if(ids.length<count)return{objects:r.objects,pending:{tool,ids},selected:ids,status:tool==="compass"?(ids.length===1?"نقطهٔ دوم شعاع را بزنید":"مرکز دایره را بزنید"):"نقطهٔ بعد را انتخاب کنید"};let next=r.objects;if(tool==="segment"||tool==="line"||tool==="ray"||tool==="circle")next=twoPointShape(next,ids[0]!,ids[1]!,tool);else if(tool==="midpoint")next=constructMidpoint(next,ids[0]!,ids[1]!);else if(tool==="perp-bisector")next=constructPerpBisector(next,ids[0]!,ids[1]!);else if(tool==="angle")next=[...next,{kind:"angle",id:newId("a"),a:ids[0]!,v:ids[1]!,b:ids[2]!,showMeasure:true}];else if(tool==="angle-bisector")next=constructAngleBisector(next,ids[0]!,ids[1]!,ids[2]!);else if(tool==="compass")next=constructCompass(next,ids[0]!,ids[1]!,ids[2]!);return{objects:next,pending:null,selected:[],status:"ساخته شد"}}
return{objects,pending,selected:[],status:""}}
export function finishPolygon(objects:GeoObject[],pending:PendingAction|null):ClickResult|null{if(!pending||pending.tool!=="polygon"||pending.ids.length<3)return null;const poly={kind:"polygon" as const,id:newId("g"),verts:pending.ids,fill:"rgba(33,86,76,.12)"};return{objects:[...objects,poly],pending:null,selected:[poly.id],status:"چندضلعی بسته شد"}}
