import { newId, recompute } from "./engine";
import type { AngleObj, CircleObj, Constraint, GeoObject, PointObj, PolygonObj, SegmentObj } from "./types";
export class Figure { objects: GeoObject[]=[];
pt(name:string,x:number,y:number,extra:Partial<PointObj>={}):PointObj{const o:PointObj={kind:"point",id:extra.id??newId("p"),name,x,y,constraint:extra.constraint??{type:"free"},...extra};this.objects.push(o);return o}
hidden(c:Constraint){return this.pt("",0,0,{hidden:true,constraint:c})} mid(n:string,a:PointObj,b:PointObj){return this.pt(n,0,0,{constraint:{type:"midpoint",a:a.id,b:b.id}})} foot(n:string,p:PointObj,a:PointObj,b:PointObj){return this.pt(n,0,0,{constraint:{type:"foot",p:p.id,a:a.id,b:b.id}})} onLine(n:string,a:PointObj,b:PointObj,t:number){return this.pt(n,0,0,{constraint:{type:"on-line",a:a.id,b:b.id,t}})} onCircle(n:string,c:PointObj,t:PointObj,angle:number){return this.pt(n,0,0,{constraint:{type:"on-circle",center:c.id,through:t.id,angle}})} reflect(n:string,s:PointObj,a:PointObj,b:PointObj){return this.pt(n,0,0,{constraint:{type:"reflect",src:s.id,a:a.id,b:b.id}})} rotate(n:string,s:PointObj,c:PointObj,angle:number){return this.pt(n,0,0,{constraint:{type:"rotate",src:s.id,center:c.id,angle}})} translate(n:string,s:PointObj,f:PointObj,t:PointObj){return this.pt(n,0,0,{constraint:{type:"translate",src:s.id,from:f.id,to:t.id}})} parallelHidden(o:PointObj,f:PointObj,t:PointObj){return this.hidden({type:"offset",origin:o.id,from:f.id,to:t.id})} perpHidden(o:PointObj,f:PointObj,t:PointObj){return this.hidden({type:"offset-perp",origin:o.id,from:f.id,to:t.id})}
intersect(n:string,a1:PointObj,b1:PointObj,a2:PointObj,b2:PointObj){return this.pt(n,0,0,{constraint:{type:"intersection-ll",a1:a1.id,b1:b1.id,a2:a2.id,b2:b2.id}})} intersectCircles(n:string,c1:PointObj,t1:PointObj,c2:PointObj,t2:PointObj,which:0|1){return this.pt(n,0,0,{constraint:{type:"intersection-cc",c1:c1.id,t1:t1.id,c2:c2.id,t2:t2.id,which}})} bisectorPoint(n:string,a:PointObj,v:PointObj,b:PointObj,dist=2.5){return this.pt(n,0,0,{constraint:{type:"on-bisector",a:a.id,v:v.id,b:b.id,dist}})}
seg(a:PointObj,b:PointObj,extra:Partial<SegmentObj>={}):SegmentObj{const o:SegmentObj={kind:"segment",id:extra.id??newId("s"),a:a.id,b:b.id,...extra};this.objects.push(o);return o} line(a:PointObj,b:PointObj,extra:any={}){const o={kind:"line" as const,id:newId("l"),a:a.id,b:b.id,...extra};this.objects.push(o);return o} ray(a:PointObj,b:PointObj,extra:any={}){const o={kind:"ray" as const,id:newId("r"),a:a.id,b:b.id,...extra};this.objects.push(o);return o}
circle(c:PointObj,t:PointObj,extra:Partial<CircleObj>={}):CircleObj{const o:CircleObj={kind:"circle",id:extra.id??newId("c"),center:c.id,through:t.id,...extra};this.objects.push(o);return o} poly(v:PointObj[],extra:Partial<PolygonObj>={}):PolygonObj{const o:PolygonObj={kind:"polygon",id:extra.id??newId("g"),verts:v.map(x=>x.id),...extra};this.objects.push(o);return o} ang(a:PointObj,v:PointObj,b:PointObj,extra:Partial<AngleObj>={}):AngleObj{const o:AngleObj={kind:"angle",id:extra.id??newId("a"),a:a.id,v:v.id,b:b.id,showMeasure:extra.showMeasure??true,...extra};this.objects.push(o);return o}
squareOn(p:PointObj,q:PointObj,ccw:boolean,extra:Partial<PolygonObj>={}):PolygonObj{const s=this.rotate("",q,p,ccw?Math.PI/2:-Math.PI/2);s.hidden=true;const r=this.translate("",s,p,q);r.hidden=true;return this.poly([p,q,r,s],extra)} build(){return recompute(this.objects)} }
