import { Figure } from "./figure";
import type { Lesson } from "./types";

const FILL = "rgba(33, 86, 76, 0.12)";
const FILL2 = "rgba(143, 61, 50, 0.10)";

export function complementary(): Lesson { return { id:"g8-complementary", grade:8, chapter:"فصل هندسهٔ هشتم", title:"متمم و مکمل", summary:"دو زاویهٔ متمم جمع ۹۰ و دو مکمل جمع ۱۸۰ می‌سازند؛ با حرکت رأس، جمع ثابت می‌ماند.", goals:["تعریف متمم و مکمل","تشخیص روی شکل مجاور","جمع زنده در پانل اندازه‌ها"], steps:[{title:"متمم",body:"در شکل بالا دو زاویه کنار هم یک قائمه ساخته‌اند. یکی را تند کنید؛ دیگری خودش را جبران می‌کند تا جمع ۹۰ بماند."},{title:"مکمل",body:"پایین، دو زاویه روی یک خط راست‌اند. جمع‌شان همیشه ۱۸۰ است. این همان پایهٔ استدلال «مجاورهای متقابل به رأس» است."},{title:"سؤال کلاسی",body:"اگر یکی از زاویه‌های متمم ۳۵ درجه باشد، دیگری چند است؟ همان سؤال را برای مکمل بپرسید."}], build(){const f=new Figure();const o=f.pt("O",-3.2,1.2),a=f.pt("A",-3.2,3.4),b=f.pt("B",-0.8,1.2),c=f.pt("C",-1.4,3.2);f.seg(o,a);f.seg(o,b);f.seg(o,c);f.ang(a,o,c);f.ang(c,o,b);const p=f.pt("P",1.6,-1.6),q=f.pt("Q",6.2,-1.6),r=f.pt("R",3.6,0.8);f.seg(p,q);f.seg(p,r);f.ang(r,p,q);const s=f.pt("S",1.6,-1.6,{hidden:true,constraint:{type:"offset",origin:p.id,from:q.id,to:p.id}});f.ang(r,p,s);return f.build();}}; }

export function exteriorAngle(): Lesson { return { id:"g8-exterior",grade:8,chapter:"مثلث",title:"زاویهٔ خارجی مثلث",summary:"با ادامه دادن یک ضلع، زاویهٔ خارجی برابر مجموع دو داخلی غیرمجاور می‌شود.",goals:["ساخت زاویهٔ خارجی","برابری با دو داخلی روبه‌رو","ارتباط با مجموع ۱۸۰°"],steps:[{title:"امتداد ضلع",body:"ضلع BC تا نقطهٔ D ادامه یافته. زاویهٔ ACD خارجی مثلث در رأس C است."},{title:"قضیه",body:"اندازهٔ زاویهٔ خارجی را با جمع دو زاویه در A و B مقایسه کنید. رأس‌ها را بکشید؛ برابری حفظ می‌شود."},{title:"ایدهٔ اثبات",body:"زاویهٔ داخلی C و خارجی مجاورش مکمل‌اند. چون داخلی‌ها جمع ۱۸۰ دارند، خارجی برابر A+B است."}],build(){const f=new Figure();const a=f.pt("A",-3.2,2.4),b=f.pt("B",-3.6,-2),c=f.pt("C",2.2,-2),d=f.onLine("D",b,c,1.45);f.poly([a,b,c],{fill:FILL});f.seg(a,b);f.seg(a,c);f.seg(b,d);f.ang(a,b,c);f.ang(c,a,b);f.ang(a,c,d);return f.build();}}; }

export function triangleInequality(): Lesson { return { id:"g8-inequality",grade:8,chapter:"مثلث",title:"نامساوی مثلث",summary:"هر ضلع از مجموع دو ضلع دیگر کوتاه‌تر است؛ وگرنه مثلث بسته نمی‌شود.",goals:["صورت نامساوی","آزمودن با سه طول","حالت تساوی یعنی نقاط هم‌خط"],steps:[{title:"سه ضلع",body:"طول هر سه ضلع روی تخته است. در پانل اندازه‌ها جمع هر دو را با سومی مقایسه کنید."},{title:"نزدیک کردن",body:"رأس C را به ضلع AB نزدیک کنید. وقتی ارتفاع تقریباً صفر شود، بزرگ‌ترین ضلع به مجموع دو تای دیگر نزدیک می‌شود."},{title:"تمرین",body:"آیا با طول‌های ۳، ۴ و ۸ می‌توان مثلث ساخت؟ با ۳، ۴ و ۵ چطور؟ روی تختهٔ خالی امتحان کنید."}],build(){const f=new Figure();const a=f.pt("A",-4,-1.6),b=f.pt("B",3.6,-1.6),c=f.pt("C",0.4,2.6);f.poly([a,b,c],{fill:FILL});f.seg(a,b,{showLength:true});f.seg(b,c,{showLength:true});f.seg(c,a,{showLength:true});return f.build();}}; }

export function triangleArea(): Lesson { return { id:"g8-triangle-area",grade:8,chapter:"مثلث",title:"مساحت مثلث",summary:"مساحت برابر نصف حاصل‌ضرب قاعده در ارتفاع متناظر است.",goals:["شناخت قاعده و ارتفاع","فرمول ۱/۲bh","ارتفاع می‌تواند بیرون مثلث منفرجه باشد"],steps:[{title:"قاعده و ارتفاع",body:"AB قاعده است و CH ارتفاع. مساحت روی شکل نوشته می‌شود. C را افقی بکشید؛ قاعده ثابت می‌ماند و ارتفاع عوض می‌شود."},{title:"حساب",body:"طول قاعده و ارتفاع را در پانل بخوانید و نصف حاصل‌ضرب را با مساحت نمایش‌داده‌شده مقایسه کنید."}],build(){const f=new Figure();const a=f.pt("A",-4.2,-1.8),b=f.pt("B",4.4,-1.8),c=f.pt("C",1.2,2.6),h=f.foot("H",c,a,b);f.poly([a,b,c],{fill:FILL,showArea:true});f.seg(a,b,{showLength:true});f.seg(b,c);f.seg(c,a);f.seg(c,h,{dashed:true,showLength:true});f.ang(c,h,b);return f.build();}}; }

export function translationLesson(): Lesson { return { id:"g8-translation",grade:8,chapter:"تبدیل‌های هندسی",title:"انتقال",summary:"هر نقطه به اندازهٔ یک بردار جابه‌جا می‌شود؛ شکل و اندازه حفظ می‌گردد.",goals:["تعریف بردار انتقال","تصویر هر رأس","حفظ طول و زاویه"],steps:[{title:"بردار",body:"پیکان UV بردار انتقال است. مثلث A′B′C′ تصویر ABC است. U یا V را بکشید تا همهٔ تصویر با هم بلغزد."},{title:"ویژگی",body:"پاره‌خط‌های واصل هر نقطه به تصویرش با بردار موازی و برابرند. طول ضلع‌ها را در دو مثلث مقایسه کنید."}],build(){const f=new Figure();const u=f.pt("U",-5.2,-2.6),v=f.pt("V",-2.4,-1.2);f.seg(u,v,{showLength:true});const a=f.pt("A",-4.4,0.2),b=f.pt("B",-1.6,-0.6),c=f.pt("C",-3.2,2.4),ap=f.translate("A′",a,u,v),bp=f.translate("B′",b,u,v),cp=f.translate("C′",c,u,v);f.poly([a,b,c],{fill:FILL});f.poly([ap,bp,cp],{fill:FILL2});f.seg(a,b);f.seg(b,c);f.seg(c,a);f.seg(ap,bp);f.seg(bp,cp);f.seg(cp,ap);f.seg(a,ap,{dashed:true});return f.build();}}; }

export function rotationLesson(): Lesson { return { id:"g8-rotation",grade:8,chapter:"تبدیل‌های هندسی",title:"دوران",summary:"دوران حول یک نقطه با زاویهٔ ثابت؛ فاصله تا مرکز حفظ می‌شود.",goals:["مرکز و زاویهٔ دوران","دوران ۹۰ و ۱۸۰ درجه","کمان فاصله تا مرکز"],steps:[{title:"مرکز O",body:"نقطهٔ A حول O به اندازهٔ ۹۰ درجه به A′ و ۱۸۰ درجه به A″ می‌رود. A را بکشید؛ فاصلهٔ OA = OA′ = OA″ می‌ماند."},{title:"مثلث",body:"کل مثلث هم ۹۰ درجه دوران یافته. از ابزار دوران ۹۰ برای ساخت تصویر تازه روی تختهٔ خالی استفاده کنید."}],build(){const f=new Figure();const o=f.pt("O",0,0),a=f.pt("A",3.2,0.6),b=f.pt("B",2.2,2.4),c=f.pt("C",4.4,2),ap=f.rotate("A′",a,o,Math.PI/2),bp=f.rotate("B′",b,o,Math.PI/2),cp=f.rotate("C′",c,o,Math.PI/2),a2=f.rotate("A″",a,o,Math.PI);f.poly([a,b,c],{fill:FILL});f.poly([ap,bp,cp],{fill:FILL2});f.seg(a,b);f.seg(b,c);f.seg(c,a);f.seg(ap,bp);f.seg(bp,cp);f.seg(cp,ap);f.seg(o,a,{dashed:true});f.seg(o,ap,{dashed:true});f.seg(o,a2,{dashed:true});f.circle(o,a,{dashed:true});return f.build();}}; }

export function equilateralConstruct(): Lesson { return { id:"g8-equilateral",grade:8,chapter:"مثلث",title:"ساخت متساوی‌الاضلاع با پرگار",summary:"دو دایره با شعاع AB از A و از B؛ یکی از برخوردها رأس سوم است.",goals:["ساخت کلاسیک با پرگار و خط‌کش","چرا هر سه ضلع برابرند","دو جواب بالا و پایین"],steps:[{title:"دو دایره",body:"دایره به مرکز A از B می‌گذرد و دایره به مرکز B از A. پس هر نقطهٔ برخورد از A و B به یک فاصله است."},{title:"رأس C",body:"C یکی از دو برخورد است. مثلث ABC متساوی‌الاضلاع است. A یا B را بکشید؛ ساخت خودش را نگه می‌دارد."},{title:"تمرین معلم",body:"از دانش‌آموز بخواهید روی تختهٔ خالی با ابزار دایره و برخورد همین ساخت را تکرار کند."}],build(){const f=new Figure();const a=f.pt("A",-2.4,-1.2),b=f.pt("B",2.4,-1.2);f.circle(a,b,{dashed:true});f.circle(b,a,{dashed:true});const c=f.intersectCircles("C",a,b,b,a,1);f.poly([a,b,c],{fill:FILL});f.seg(a,b,{marks:1,showLength:true});f.seg(b,c,{marks:1,showLength:true});f.seg(c,a,{marks:1,showLength:true});f.ang(c,a,b);f.ang(a,b,c);f.ang(b,c,a);return f.build();}}; }

export function centroidLesson(): Lesson { return { id:"g9-centroid",grade:9,chapter:"خطوط ویژهٔ مثلث",title:"میانه‌ها و مرکز ثقل",summary:"سه میانه در یک نقطه هم‌رس‌اند و این نقطه هر میانه را به نسبت ۲ به ۱ تقسیم می‌کند.",goals:["تعریف میانه","هم‌رسی سه میانه","نسبت ۲:۱ از رأس به وسط ضلع"],steps:[{title:"وسط اضلاع",body:"D، E و F وسط اضلاع‌اند. میانه‌ها AD، BE و CF در G به هم می‌رسند."},{title:"نسبت",body:"طول AG و GD را مقایسه کنید. AG باید حدود دو برابر GD باشد. رأس را بکشید و نسبت را دوباره ببینید."}],build(){const f=new Figure();const a=f.pt("A",0,3.2),b=f.pt("B",-4.2,-2),c=f.pt("C",4.4,-2),d=f.mid("D",b,c),e=f.mid("E",a,c),g=f.mid("F",a,b),p=f.intersect("G",a,d,b,e);f.poly([a,b,c],{fill:FILL});f.seg(a,b);f.seg(b,c);f.seg(c,a);f.seg(a,d,{showLength:true});f.seg(b,e);f.seg(c,g);void p;return f.build();}}; }

export function circumcenterLesson(): Lesson { return { id:"g9-circumcenter",grade:9,chapter:"خطوط ویژهٔ مثلث",title:"دایرهٔ محیطی مثلث",summary:"عمودمنصف‌های اضلاع در یک نقطه هم‌رس‌اند؛ آن نقطه مرکز دایره‌ای است که از هر سه رأس می‌گذرد.",goals:["عمودمنصف","مرکز دایرهٔ محیطی","شعاع تا رأس‌ها برابر است"],steps:[{title:"عمودمنصف‌ها",body:"وسط هر ضلع و خط عمود بر آن رسم شده. برخوردشان O است."},{title:"دایره",body:"دایره به مرکز O از A می‌گذرد و ناچار از B و C هم می‌گذرد. مثلث را بکشید؛ O ممکن است داخل، روی وتر یا بیرون باشد."}],build(){const f=new Figure();const a=f.pt("A",0,3),b=f.pt("B",-4,-1.8),c=f.pt("C",3.8,-1.6),m=f.mid("M",b,c),n=f.mid("N",a,c),hm=f.perpHidden(m,b,c),hn=f.perpHidden(n,a,c),o=f.intersect("O",m,hm,n,hn);f.poly([a,b,c],{fill:FILL});f.seg(a,b);f.seg(b,c);f.seg(c,a);f.line(m,hm,{dashed:true});f.line(n,hn,{dashed:true});f.circle(o,a);f.seg(o,a,{dashed:true,showLength:true});return f.build();}}; }

export function incenterLesson(): Lesson { return { id:"g9-incenter",grade:9,chapter:"خطوط ویژهٔ مثلث",title:"دایرهٔ محاطی مثلث",summary:"نیمسازهای زاویه در یک نقطه هم‌رس‌اند؛ فاصلهٔ این نقطه تا هر سه ضلع برابر است.",goals:["نیمساز زاویه","مرکز دایرهٔ محاطی","شعاع همان فاصله تا ضلع است"],steps:[{title:"نیمسازها",body:"از دو رأس نیمساز کشیده‌ایم. برخورد I مرکز دایرهٔ محاطی است."},{title:"مماس بودن",body:"پای عمود از I به BC نقطهٔ تماس است. دایره هر سه ضلع را از داخل لمس می‌کند. رأس را حرکت دهید."}],build(){const f=new Figure();const a=f.pt("A",0,3.2),b=f.pt("B",-4.2,-2),c=f.pt("C",4.2,-2),pa=f.bisectorPoint("",b,a,c,3.2),pb=f.bisectorPoint("",a,b,c,3.2);pa.hidden=true;pb.hidden=true;const i=f.intersect("I",a,pa,b,pb),t=f.foot("T",i,b,c);f.poly([a,b,c],{fill:FILL});f.seg(a,b);f.seg(b,c);f.seg(c,a);f.ray(a,pa,{dashed:true});f.ray(b,pb,{dashed:true});f.circle(i,t);f.seg(i,t,{dashed:true,showLength:true});f.ang(i,t,c);return f.build();}}; }

export function altitudesLesson(): Lesson { return { id:"g9-altitudes",grade:9,chapter:"خطوط ویژهٔ مثلث",title:"ارتفاع‌ها و نقطهٔ ارتفاعی",summary:"سه ارتفاع مثلث در یک نقطه (ارتوسنتر) هم‌رس‌اند.",goals:["تعریف ارتفاع","هم‌رسی سه ارتفاع","جای نقطه در مثلث حاد و منفرجه"],steps:[{title:"پای عمود",body:"از هر رأس به ضلع روبه‌رو عمود شده. H برخورد دو ارتفاع است؛ سومی هم از همان نقطه می‌گذرد."},{title:"نوع مثلث",body:"رأس را طوری بکشید که زاویه منفرجه شود؛ می‌بینید H از مثلث بیرون می‌رود."}],build(){const f=new Figure();const a=f.pt("A",0,3.1),b=f.pt("B",-3.8,-1.8),c=f.pt("C",4,-1.6),ha=f.foot("D",a,b,c),hb=f.foot("E",b,a,c),h=f.intersect("H",a,ha,b,hb);f.poly([a,b,c],{fill:FILL});f.seg(a,b);f.seg(b,c);f.seg(c,a);f.seg(a,ha,{dashed:true});f.seg(b,hb,{dashed:true});f.ang(a,ha,c);f.ang(b,hb,a);void h;return f.build();}}; }

export function midpointCoord(): Lesson { return { id:"g9-midpoint-coord",grade:9,chapter:"خط و مختصات",title:"وسط پاره‌خط در مختصات",summary:"مختصات وسط، میانگین مختصات دو سر است.",goals:["فرمول وسط","خواندن از روی شبکه","ارتباط با میانه"],steps:[{title:"دو نقطه",body:"A و B را روی شبکه جابه‌جا کنید. M وسط است. مختصات را در پانل ویژگی با میانگین x و y مقایسه کنید."},{title:"فرمول",body:"M = ((x_A + x_B)/2 ، (y_A + y_B)/2). محورها را روشن نگه دارید."}],build(){const f=new Figure();const a=f.pt("A",-4,-2),b=f.pt("B",5,3);f.seg(a,b,{showLength:true});f.mid("M",a,b);return f.build();}}; }

export const MORE_LESSONS: Lesson[] = [complementary(),exteriorAngle(),triangleInequality(),triangleArea(),equilateralConstruct(),translationLesson(),rotationLesson(),centroidLesson(),altitudesLesson(),circumcenterLesson(),incenterLesson(),midpointCoord()];
