export type Vec={x:number;y:number}; export const EPS=1e-8;
export const add=(a:Vec,b:Vec):Vec=>({x:a.x+b.x,y:a.y+b.y}); export const sub=(a:Vec,b:Vec):Vec=>({x:a.x-b.x,y:a.y-b.y}); export const mul=(a:Vec,s:number):Vec=>({x:a.x*s,y:a.y*s}); export const dot=(a:Vec,b:Vec):number=>a.x*b.x+a.y*b.y; export const cross=(a:Vec,b:Vec):number=>a.x*b.y-a.y*b.x; export const len=(a:Vec):number=>Math.hypot(a.x,a.y); export const dist=(a:Vec,b:Vec):number=>Math.hypot(a.x-b.x,a.y-b.y); export const dist2=(a:Vec,b:Vec):number=>{const dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy}; export function norm(a:Vec):Vec{const l=len(a);return l<EPS?{x:0,y:0}:{x:a.x/l,y:a.y/l}}; export const perp=(a:Vec):Vec=>({x:-a.y,y:a.x}); export const lerp=(a:Vec,b:Vec,t:number):Vec=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});
export function closestT(a:Vec,b:Vec,p:Vec){const ab=sub(b,a),l2=dot(ab,ab);return l2<EPS?0:dot(sub(p,a),ab)/l2} export const projectPointToLine=(p:Vec,a:Vec,b:Vec)=>lerp(a,b,closestT(a,b,p)); export const distPointToLine=(p:Vec,a:Vec,b:Vec)=>dist(p,projectPointToLine(p,a,b)); export function distPointToSegment(p:Vec,a:Vec,b:Vec){return dist(p,lerp(a,b,Math.max(0,Math.min(1,closestT(a,b,p)))))} export function distPointToRay(p:Vec,a:Vec,b:Vec){return dist(p,lerp(a,b,Math.max(0,closestT(a,b,p))))}
export function lineLineIntersection(a:Vec,b:Vec,c:Vec,d:Vec):Vec|null{const r=sub(b,a),s=sub(d,c),den=cross(r,s);if(Math.abs(den)<EPS)return null;return lerp(a,b,cross(sub(c,a),s)/den)}
export function lineCircleIntersection(a:Vec,b:Vec,c:Vec,r:number):Vec[]{const d=sub(b,a),f=sub(a,c),A=dot(d,d),B=2*dot(f,d),C=dot(f,f)-r*r,disc=B*B-4*A*C;if(disc<-EPS||A<EPS)return[];const q=Math.sqrt(Math.max(0,disc)),t1=(-B-q)/(2*A),t2=(-B+q)/(2*A);const out=[lerp(a,b,t1)];if(disc>EPS)out.push(lerp(a,b,t2));return out}
export function circleCircleIntersection(c1:Vec,r1:number,c2:Vec,r2:number):Vec[]{const d=dist(c1,c2);if(d<EPS||d>r1+r2+EPS||d<Math.abs(r1-r2)-EPS)return[];const a=(r1*r1-r2*r2+d*d)/(2*d),h=Math.sqrt(Math.max(0,r1*r1-a*a)),p=lerp(c1,c2,a/d),dir=norm(sub(c2,c1)),q=perp(dir);return h<EPS?[p]:[add(p,mul(q,h)),add(p,mul(q,-h))]}
export const reflectPoint=(p:Vec,a:Vec,b:Vec):Vec=>{const pr=projectPointToLine(p,a,b);return add(pr,sub(pr,p))}; export function rotateAround(p:Vec,c:Vec,ang:number):Vec{const v=sub(p,c),cs=Math.cos(ang),sn=Math.sin(ang);return{x:c.x+v.x*cs-v.y*sn,y:c.y+v.x*sn+v.y*cs}}
export function angleDeg(a:Vec,v:Vec,b:Vec){const ua=sub(a,v),ub=sub(b,v),la=len(ua),lb=len(ub);if(la<EPS||lb<EPS)return 0;return Math.acos(Math.max(-1,Math.min(1,dot(ua,ub)/(la*lb))))*180/Math.PI} export function orientedAngle(a:Vec,v:Vec,b:Vec){const start=Math.atan2(a.y-v.y,a.x-v.x),end=Math.atan2(b.y-v.y,b.x-v.x);let sweep=end-start;while(sweep<=-Math.PI)sweep+=Math.PI*2;while(sweep>Math.PI)sweep-=Math.PI*2;return{start,end:start+sweep,sweep}}
export function polygonArea(v:Vec[]){let s=0;for(let i=0;i<v.length;i++){const p=v[i]!,q=v[(i+1)%v.length]!;s+=p.x*q.y-q.x*p.y}return Math.abs(s)/2} export function polygonCentroid(v:Vec[]){if(!v.length)return{x:0,y:0};let x=0,y=0;for(const p of v){x+=p.x;y+=p.y}return{x:x/v.length,y:y/v.length}} export const almostEqual=(a:number,b:number,tol=.4)=>Math.abs(a-b)<=tol; export const snapToGrid=(p:Vec,step:number):Vec=>({x:Math.round(p.x/step)*step,y:Math.round(p.y/step)*step}); export const isRightAngle=(a:Vec,v:Vec,b:Vec,tolDeg=.8)=>almostEqual(angleDeg(a,v,b),90,tolDeg);
