import { pointById } from "./engine";
import { faNum } from "./format";
import { add, angleDeg, dist, isRightAngle, lerp, mul, norm, orientedAngle, polygonArea, polygonCentroid, sub, type Vec } from "./math";
import { canvasTheme as T } from "./theme";
import type { GeoObject, PendingAction, PointObj } from "./types";

export interface Camera { scale: number; ox: number; oy: number; }
export interface RenderState { objects: GeoObject[]; camera: Camera; width: number; height: number; dpr: number; selected: string[]; hoverId: string | null; highlight: string[]; pending: PendingAction | null; cursor: Vec | null; settings: { grid: boolean; axes: boolean; labels: boolean; measurements: boolean; }; }
export function worldToScreen(cam: Camera, x: number, y: number): Vec { return { x: cam.ox + x * cam.scale, y: cam.oy - y * cam.scale }; }
export function screenToWorld(cam: Camera, x: number, y: number): Vec { return { x: (x - cam.ox) / cam.scale, y: (cam.oy - y) / cam.scale }; }
function s(cam: Camera, p: Vec): Vec { return worldToScreen(cam, p.x, p.y); }
function colorOf(o: { color?: string }, fallback = T.ink): string { return o.color ?? fallback; }
function isHi(id: string, selected: string[], hoverId: string | null, highlight: string[]) { return selected.includes(id) || hoverId === id || highlight.includes(id); }
function setStroke(ctx: CanvasRenderingContext2D, color: string, width: number, dashed = false) { ctx.strokeStyle = color; ctx.lineWidth = width; ctx.setLineDash(dashed ? [7, 5] : []); ctx.lineCap = "round"; ctx.lineJoin = "round"; }
function extendLine(a: Vec, b: Vec, len: number): [Vec, Vec] { const d = norm(sub(b, a)); return [add(a, mul(d, -len)), add(a, mul(d, len))]; }
function extendRay(a: Vec, b: Vec, len: number): [Vec, Vec] { const d = norm(sub(b, a)); return [a, add(a, mul(d, len))]; }
function drawGrid(ctx: CanvasRenderingContext2D, st: RenderState) { const { camera: cam, width, height } = st; const topLeft = screenToWorld(cam, 0, 0); const botRight = screenToWorld(cam, width, height); const x0 = Math.floor(topLeft.x) - 1; const x1 = Math.ceil(botRight.x) + 1; const y0 = Math.floor(botRight.y) - 1; const y1 = Math.ceil(topLeft.y) + 1; for (let x = x0; x <= x1; x++) { const p = worldToScreen(cam, x, 0); setStroke(ctx, x % 5 === 0 ? T.gridMajor : T.grid, x % 5 === 0 ? 1 : 0.6); ctx.beginPath(); ctx.moveTo(p.x, 0); ctx.lineTo(p.x, height); ctx.stroke(); } for (let y = y0; y <= y1; y++) { const p = worldToScreen(cam, 0, y); setStroke(ctx, y % 5 === 0 ? T.gridMajor : T.grid, y % 5 === 0 ? 1 : 0.6); ctx.beginPath(); ctx.moveTo(0, p.y); ctx.lineTo(width, p.y); ctx.stroke(); } }
function drawAxes(ctx: CanvasRenderingContext2D, st: RenderState) { const { camera: cam, width, height } = st; const o = worldToScreen(cam, 0, 0); setStroke(ctx, T.axis, 1.4); ctx.beginPath(); ctx.moveTo(0, o.y); ctx.lineTo(width, o.y); ctx.stroke(); ctx.beginPath(); ctx.moveTo(o.x, 0); ctx.lineTo(o.x, height); ctx.stroke(); ctx.fillStyle = T.muted; ctx.font = "500 11px Vazirmatn, sans-serif"; ctx.textAlign = "left"; ctx.textBaseline = "top"; ctx.fillText("x", width - 16, o.y + 6); ctx.fillText("y", o.x + 8, 8); }
function drawTickMarks(ctx: CanvasRenderingContext2D, a: Vec, b: Vec, marks: number, color: string) { const mid = lerp(a, b, 0.5); const d = norm(sub(b, a)); const n = { x: -d.y, y: d.x }; const span = 5; for (let i = 0; i < marks; i++) { const off = (i - (marks - 1) / 2) * 5; const c = add(mid, mul(d, off)); const p1 = add(c, mul(n, span)); const p2 = add(c, mul(n, -span)); setStroke(ctx, color, 1.6); ctx.beginPath(); ctx.moveTo(p1.x, p1.y); ctx.lineTo(p2.x, p2.y); ctx.stroke(); } }
export function renderBoard(ctx: CanvasRenderingContext2D, st: RenderState) {
  const { camera: cam, width, height, dpr } = st; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, width, height); ctx.fillStyle = T.paper; ctx.fillRect(0, 0, width, height); if (st.settings.grid) drawGrid(ctx, st); if (st.settings.axes) drawAxes(ctx, st);
  const pts = pointById(st.objects); const big = 4000 / Math.max(cam.scale, 1); const { selected, hoverId, highlight } = st;
  for (const o of st.objects) { if (o.kind !== "polygon") continue; const verts = o.verts.map((id) => pts.get(id)).filter((p): p is PointObj => !!p); if (verts.length < 3) continue; ctx.beginPath(); const first = s(cam, verts[0]!); ctx.moveTo(first.x, first.y); for (let i = 1; i < verts.length; i++) { const p = s(cam, verts[i]!); ctx.lineTo(p.x, p.y); } ctx.closePath(); ctx.fillStyle = o.fill ?? T.accentFill; ctx.fill(); const hi = isHi(o.id, selected, hoverId, highlight); setStroke(ctx, hi ? T.accent : colorOf(o), hi ? 2.4 : 1.6); ctx.stroke(); if (st.settings.measurements && (o.showArea || hi)) { const c = s(cam, polygonCentroid(verts)); ctx.fillStyle = T.ink; ctx.font = "500 12px Vazirmatn, sans-serif"; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(`${faNum(polygonArea(verts), 1)}`, c.x, c.y); } }
  for (const o of st.objects) { if (o.kind !== "circle") continue; const c = pts.get(o.center), t = pts.get(o.through); if (!c || !t) continue; const cs = s(cam, c), r = dist(c, t) * cam.scale, hi = isHi(o.id, selected, hoverId, highlight); ctx.beginPath(); ctx.arc(cs.x, cs.y, Math.max(r, 0.5), 0, Math.PI * 2); ctx.fillStyle = hi ? T.accentFill : "transparent"; if (hi) ctx.fill(); setStroke(ctx, hi ? T.accent : colorOf(o), hi ? 2.2 : 1.5, o.dashed); ctx.stroke(); }
  for (const o of st.objects) { if (o.kind !== "line" && o.kind !== "ray" && o.kind !== "segment") continue; const a = pts.get(o.a), b = pts.get(o.b); if (!a || !b) continue; const sa = s(cam, a), sb = s(cam, b), hi = isHi(o.id, selected, hoverId, highlight); let p1 = sa, p2 = sb; if (o.kind === "line") [p1, p2] = extendLine(sa, sb, big); else if (o.kind === "ray") [p1, p2] = extendRay(sa, sb, big); setStroke(ctx, hi ? T.accent : colorOf(o), hi ? 2.4 : 1.7, o.dashed); ctx.beginPath(); ctx.moveTo(p1.x, p1.y); ctx.lineTo(p2.x, p2.y); ctx.stroke(); if (o.kind === "segment" && o.marks) drawTickMarks(ctx, sa, sb, o.marks, hi ? T.accent : colorOf(o)); if (o.kind === "segment" && st.settings.measurements && (o.showLength || hi)) { const mid = lerp(sa, sb, 0.5), d = norm(sub(sb, sa)), n = { x: -d.y, y: d.x }, label = add(mid, mul(n, 14)); ctx.fillStyle = T.ink; ctx.font = "500 12px Vazirmatn, sans-serif"; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(faNum(dist(a, b), 1), label.x, label.y); } }
  for (const o of st.objects) { if (o.kind !== "angle") continue; const a = pts.get(o.a), v = pts.get(o.v), b = pts.get(o.b); if (!a || !v || !b) continue; const sa = s(cam, a), sv = s(cam, v), sb = s(cam, b), hi = isHi(o.id, selected, hoverId, highlight), col = hi ? T.accent : (o.color ?? T.angle), r = 28; if (isRightAngle(a, v, b)) { const ua = mul(norm(sub(sa, sv)), r * 0.7), ub = mul(norm(sub(sb, sv)), r * 0.7), p1 = add(sv, ua), p2 = add(p1, ub), p3 = add(sv, ub); setStroke(ctx, col, 1.6); ctx.beginPath(); ctx.moveTo(p1.x, p1.y); ctx.lineTo(p2.x, p2.y); ctx.lineTo(p3.x, p3.y); ctx.stroke(); } else { const { start, sweep } = orientedAngle(sa, sv, sb); ctx.beginPath(); ctx.arc(sv.x, sv.y, r, -start, -(start + sweep), sweep > 0); setStroke(ctx, col, hi ? 2.2 : 1.6); ctx.stroke(); } if (st.settings.measurements && (o.showMeasure || hi)) { const { start, sweep } = orientedAngle(sa, sv, sb), mid = start + sweep / 2, lx = sv.x + Math.cos(mid) * (r + 16), ly = sv.y - Math.sin(mid) * (r + 16); ctx.fillStyle = col; ctx.font = "600 12px Vazirmatn, sans-serif"; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(`${faNum(angleDeg(a, v, b), 0)}°`, lx, ly); } }
  if (st.pending && st.cursor && st.pending.ids.length > 0) { const last = pts.get(st.pending.ids[st.pending.ids.length - 1]!); if (last) { const a = s(cam, last), b = s(cam, st.cursor); setStroke(ctx, T.ghost, 1.4, true); if (st.pending.tool === "circle") { ctx.beginPath(); ctx.arc(a.x, a.y, dist(a, b), 0, Math.PI * 2); ctx.stroke(); } else if (st.pending.tool === "polygon") { ctx.beginPath(); const first = pts.get(st.pending.ids[0]!); if (first) { const f = s(cam, first); ctx.moveTo(f.x, f.y); for (let i = 1; i < st.pending.ids.length; i++) { const p = pts.get(st.pending.ids[i]!); if (!p) continue; const sp = s(cam, p); ctx.lineTo(sp.x, sp.y); } ctx.lineTo(b.x, b.y); ctx.stroke(); } } else { ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); } } }
  for (const o of st.objects) { if (o.kind !== "point" || o.hidden) continue; const p = s(cam, o), hi = isHi(o.id, selected, hoverId, highlight), r = hi ? 6 : 5; ctx.beginPath(); ctx.arc(p.x, p.y, r, 0, Math.PI * 2); ctx.fillStyle = T.pointFill; ctx.fill(); setStroke(ctx, hi ? T.accent : colorOf(o), hi ? 2.4 : 1.8); ctx.stroke(); if (st.settings.labels && o.name) { ctx.fillStyle = T.ink; ctx.font = "600 13px Vazirmatn, sans-serif"; ctx.textAlign = "left"; ctx.textBaseline = "bottom"; const label = st.settings.axes ? `${o.name} (${faNum(o.x, 1)}٬ ${faNum(o.y, 1)})` : o.name; ctx.fillText(label, p.x + 8, p.y - 6); } }
}
export function exportCanvasPng(canvas: HTMLCanvasElement): string { return canvas.toDataURL("image/png"); }
