import { create } from "zustand"; import { finishPolygon, handleCanvasClick } from "./actions"; import { bumpIdSeqFrom, collectMeasures, deleteWithDependents, recompute, renamePoint, toggleShow, tryMovePoint } from "./engine"; import { getLesson } from "./lessons"; import { buildTemplate } from "./templates"; import type { BoardSettings,GeoObject,Measure,PendingAction,TemplateId,Tool } from "./types";
const STORAGE_KEY="pargar-v2"; export const defaultSettings:BoardSettings={grid:true,axes:false,snap:true,labels:true,measurements:true};
interface Persisted{objects:GeoObject[];settings:BoardSettings;lessonId:string|null;lessonStep:number;started:boolean} function loadPersisted():Partial<Persisted>|null{if(typeof window==="undefined")return null;try{const raw=localStorage.getItem(STORAGE_KEY)??localStorage.getItem("pargar-v1");return raw?JSON.parse(raw):null}catch{return null}}
interface BoardState{objects:GeoObject[];selected:string[];tool:Tool;pending:PendingAction|null;settings:BoardSettings;lessonId:string|null;lessonStep:number;history:GeoObject[][];future:GeoObject[][];started:boolean;status:string;fitNonce:number;hydrated:boolean;hydrate:()=>void;persist:()=>void;startBlank:()=>void;setTool:(tool:Tool)=>void;click:(world:{x:number;y:number},scale:number,hitId:string|null,hitKind:string|null)=>void;movePoint:(id:string,x:number,y:number)=>void;commitHistory:()=>void;select:(ids:string[])=>void;undo:()=>void;redo:()=>void;loadLesson:(id:string)=>void;setLessonStep:(step:number)=>void;newBoard:()=>void;toggleSetting:(key:keyof BoardSettings)=>void;removeSelected:()=>void;toggleMeasure:(id:string)=>void;finishPending:()=>void;cancelPending:()=>void;setStatus:(status:string)=>void;renameSelected:(name:string)=>void;insertTemplate:(id:TemplateId)=>void;fitView:()=>void;measures:()=>Measure[]}
const pushHist=(h:GeoObject[][],o:GeoObject[])=>[...h.slice(-40),structuredClone(o)]; const COORD_LESSONS=new Set(["g8-coordinates","g9-distance","g9-midpoint-coord"]);
export const useBoard=create<BoardState>((set,get)=>({objects:[],selected:[],tool:"select",pending:null,settings:defaultSettings,lessonId:null,lessonStep:0,history:[],future:[],started:false,status:"",fitNonce:0,hydrated:false,
hydrate:()=>{const s=loadPersisted();if(!s){set({hydrated:true});return}const objects=s.objects??[];bumpIdSeqFrom(objects);set({objects,settings:{...defaultSettings,...s.settings},lessonId:s.lessonId??null,lessonStep:s.lessonStep??0,started:s.started??objects.length>0,hydrated:true,fitNonce:1})},
persist:()=>{if(typeof window==="undefined")return;const s=get();const d:Persisted={objects:s.objects,settings:s.settings,lessonId:s.lessonId,lessonStep:s.lessonStep,started:s.started};try{localStorage.setItem(STORAGE_KEY,JSON.stringify(d))}catch{}},
startBlank:()=>{set({started:true,objects:[],selected:[],pending:null,lessonId:null,lessonStep:0,history:[],future:[],fitNonce:get().fitNonce+1,status:"تختهٔ خالی — از نوار ابزار شکل بکشید"});get().persist()},
setTool:tool=>set({tool,pending:null,status:""}),
click:(world,scale,hitId,hitKind)=>{const s=get(),r=handleCanvasClick(s.objects,s.tool,s.pending,world,scale,s.settings.snap,hitId,hitKind);set({objects:r.objects,pending:r.pending,selected:r.selected,status:r.status,history:r.objects!==s.objects?pushHist(s.history,s.objects):s.history,future:r.objects!==s.objects?[]:s.future});get().persist()},
commitHistory:()=>{const s=get();set({history:pushHist(s.history,s.objects),future:[]})}, movePoint:(id,x,y)=>set({objects:tryMovePoint(get().objects,id,x,y,get().settings.snap)}), select:ids=>set({selected:ids}),
undo:()=>{const s=get(),p=s.history.at(-1);if(!p)return;set({objects:p,history:s.history.slice(0,-1),future:[s.objects,...s.future],selected:[],pending:null});get().persist()},
redo:()=>{const s=get(),n=s.future[0];if(!n)return;set({objects:n,future:s.future.slice(1),history:pushHist(s.history,s.objects),selected:[]});get().persist()},
loadLesson:id=>{const l=getLesson(id);if(!l)return;const objects=recompute(l.build());bumpIdSeqFrom(objects);set({started:true,objects,lessonId:id,lessonStep:0,selected:[],pending:null,tool:"select",history:[],future:[],settings:{...get().settings,axes:COORD_LESSONS.has(id)?true:get().settings.axes,grid:true},fitNonce:get().fitNonce+1,status:l.title});get().persist()},
setLessonStep:step=>{set({lessonStep:step});get().persist()},newBoard:()=>{set({objects:[],selected:[],pending:null,lessonId:null,lessonStep:0,history:[],future:[],tool:"select",fitNonce:get().fitNonce+1,status:"تختهٔ خالی",started:true});get().persist()},toggleSetting:key=>{set({settings:{...get().settings,[key]:!get().settings[key]}});get().persist()},
removeSelected:()=>{const s=get();if(!s.selected.length)return;set({history:pushHist(s.history,s.objects),future:[],objects:deleteWithDependents(s.objects,s.selected),selected:[]});get().persist()},toggleMeasure:id=>{set({objects:toggleShow(get().objects,id)});get().persist()},
finishPending:()=>{const s=get(),d=finishPolygon(s.objects,s.pending);if(!d)return;set({history:pushHist(s.history,s.objects),objects:d.objects,pending:d.pending,selected:d.selected,status:d.status,future:[]});get().persist()},cancelPending:()=>set({pending:null,status:""}),setStatus:status=>set({status}),
renameSelected:name=>{const s=get(),id=s.selected[0];if(!id)return;set({objects:renamePoint(s.objects,id,name)});get().persist()},
insertTemplate:id=>{const s=get(),extra=buildTemplate(id);bumpIdSeqFrom([...s.objects,...extra]);set({history:pushHist(s.history,s.objects),future:[],objects:recompute([...s.objects,...extra]),selected:[],pending:null,lessonId:null,started:true,fitNonce:s.fitNonce+1,status:"شکل آماده اضافه شد"});get().persist()},fitView:()=>set({fitNonce:get().fitNonce+1}),measures:()=>collectMeasures(get().objects)}));
